<?php
/**
 * Private Entrepreneur Anatolii Lehkyi (aka Lanot)
 *
 * @category    Lanot
 * @package     Lanot_Rule
 * @copyright   Copyright (c) 2010 Anatolii Lehkyi
 * @license     http://opensource.org/licenses/osl-3.0.php
 * @link        http://www.lanot.biz/
 */
?>
<script type="text/javascript">
//<![CDATA[
document.observe("dom:loaded", hideShowSubproductOptions($('rule_sub_is_enable')));

function hideShowSubproductOptions(enabler)
{
    if (enabler.value == 1) {
        $('rule_sub_simple_action').parentNode.parentNode.show();
        $('rule_sub_discount_amount').parentNode.parentNode.show();
        $('rule_sub_discount_amount').addClassName('required-entry validate-not-negative-number');
    } else {
        $('rule_sub_simple_action').parentNode.parentNode.hide();
        $('rule_sub_discount_amount').parentNode.parentNode.hide();
        $('rule_sub_discount_amount').removeClassName('required-entry').removeClassName('validate-not-negative-number');
    }
}
//]]>
</script>
